name: Get Key

on:
  workflow_dispatch:
  schedule:
  - cron: '*/10 * * * *'

jobs:
  Get-Key:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
      
    - uses: actions/checkout@v3
    - name: Delete Workflow History
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 0

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install httpx click
    - name: Run Code
      run: python3 .github/main.py --key ${{ secrets.KEY }}
    - name: Commit
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        add: "key.txt --force"
        message: "Goofy Ahhhh"
        tag_push: '--force'
